# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Polytope
subtitle: Computational Design and Creative Coding
email: polytope.solutions@gmail.com
description: Website for autonomo project of Daniil Koshelyuk.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.polytope.solutions" # the base hostname & protocol for your site, e.g. http://example.com

contacts:
    - content:
        type:               github
        url:                https://github.com/DKFactotum
    - content:
        type:               gitlab
        url:                https://gitlab.fabcloud.org/daniil.koshelyuk
    - content:
        type:               personla site
        url:                https://daniil.koshelyuk.site
    - content:
        type:               LinkedIn
        url:                https://www.linkedin.com/in/dkfactotum/
    # - twitter:
    #     type:             twitter
    #     url:              https://twitter.com/dkfactotum

# Default values for front matter
defaults:
    - scope:
        path:               ""
      values:
        author:             Daniil Koshelyuk
    - scope:
        path:               "/assets/images/"
      values:
        image:              true

# Build settings
theme:                      minima
markdown:                   kramdown
plugins:
  - jekyll-feed
  - jekyll-datapage-generator

# Pages to Auto generate
# page_gen-dirs:              true
page_gen:
    - data:                 'services'
      template:             'service'
      name:                 'serviceName'
      dir:                  'services'
      title:                'serviceName'

sass:
    sass_dir:               _sass
    style:                  compressed

# GitHub Pages
lsi:                        false
safe:                       true
incremental:                false
highlighter:                rouge
gist:
    noscript:               false
kramdown:
    math_engine:            mathjax
    syntax_highlighter:     rouge

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
