-   serviceName: Interactive-Visualization
    lang:
        Eng: Interactive Visualization
        Esp: Visualización interactiva
        Cat: Visualització interactiva
    description:
        Eng: >
            <b>Interactive visualization</b> encompasses use of <b>new medium tools</b> to convey the story behind projects to <b>involve target audience</b> on a deeper level and experience projects in a new and specifically tailored way.
            <br>
            <br>
            Each project, depending on the focus and the idea, can be best conveyed in various ways. Mediums Polytope has experience with are:<br><b>
                - Virtual Reailty (standalone or mobile);<br>
                - Web 3D;<br>
                - Augmented Reality (standalona or mobile);<br>
                - Projections;<br>
                - Sensors and actuators.</b>
            <br>
            <br>
            These vary in <b>visual fidelity, types of interaction, scalability, accessibility</b>. Some projects may require combinations of specific aspects.
            <br>
            <br>
            <b>Polytope</b> can provide <b>analysis</b> of idea to fit interactive system and <b>plan steps of development</b>; <b>organization of existing projects</b> to work for it; setup of <b>basic necessary systems</b>; development of <b>custom behaviors</b> necessary for interaction, activation of virtual assets, and User Experiencs (UX); as well as developing <b>details for virtual environments</b>; or <b>support, documentation and guidance</b> in the development.
        Esp: >
            La <b>visualización interactiva</b> abarca el uso de <b>nuevas herramientas de medios</b> para transmitir la historia detrás de los proyectos para <b>involucrar al público objetivo</b> en un nivel más profundo y experimentar los proyectos de una manera nueva y de forma específicamente adaptada.
            <br>
            <br>
            Cada proyecto, según el enfoque y la idea, puede transmitirse mejor de varias formas. Los medios con los que Polytope tiene experiencia son:<br><b>
                -Realidad Virtual(independiente o móvil);<br>
                - Web 3D;<br>
                - Realidad Aumentada (independiente o móvil);<br>
                - Proyecciones;<br>
                - Sensores y actuadores.</b>
            <br>
            <br>
            Estos varían en <b>fidelidad visual, tipos de interacción, escalabilidad, accesibilidad</b>. Algunos proyectos pueden requerir combinaciones de aspectos específicos.
            <br>
            <br>
            <b>Polytope</b> puede proporcionar <b>análisis</b> de la idea para que se ajuste al sistema interactivo y <b>planificar los pasos del desarrollo</b>; <b>organización de proyectos existentes</b> para funcionar con estos medios; configuración de <b>sistemas básicos necesarios</b>; desarrollo de <b>comportamientos personalizados</b> necesarios para la interacción, activación de activos virtuales y experiencias de usuario (UX); además de desarrollar <b>detalles para entornos virtuales</b>; o incluso <b>soporte, documentación y orientación</b> en el processo de desarrollo.
        Cat: >
            La <b>visualització interactiva</b> abasta l'ús de <b>noves eines de mitjans</b> per transmetre la història darrere dels projectes per <b>involucrar el públic objectiu</b> en un nivell més profund i experimentar els projectes d'una manera nova i de forma específicament adaptada.
            <br>
            <br>
            Cada projecte, segons l'enfocament i la idea, pot transmetre millor de diverses formes. Els mitjans amb els quals Polytope té experiència són:<br><b>
                - Realitat Virtual (independent o mòbil);<br>
                - Web 3D;<br>
                - Realitat Augmentada (independent o mòbil);<br>
                - Projeccions;<br>
                - Sensors i actuadors.</b>
            <br>
            <br>
            Aquests varien en <b>fidelitat visual, tipus d'interacció, escalabilitat, accessibilitat</b>. Alguns projectes poden requerir combinacions d'aspectes específics.
            <br>
            <br>
            <b>Polytope</b> pot proporcionar <b>anàlisi</b> de la idea perquè s'ajusti a sistema interactiu i <b>planificar els passos de el desenvolupament</b>; <b>organització de projectes existents</b> per a funcionar amb aquests mitjans; configuració de <b>sistemes bàsics necessaris</b>; desenvolupament de <b>comportaments personalitzats</b> necessaris per a la interacció, activació d'actius virtuals i experiències d'usuari (UX); a més de desenvolupar <b>detalls per a entorns virtuals</b>; o fins i tot <b>suport, documentació i orientació</b> en el proces de desenvolupament.

-   serviceName: Parametric-Design
    lang:
        Eng: Parametric Design
        Esp: Diseño Paramétrico
        Cat: Disseny piramètric
    description:
        Eng: >
            In the modern era <b>computation</b> and <b>design</b> have become inseparable. Our tools make it possible to <b>express</b> our ideas but also enforce a unique <b>way of thinking</b> thus opening up new and unique solutions.
            <br>
            <br>
            Term <b>parametric design</b> refers to an approach where design is treated as a <b>protocol</b> rather than a standalone result. In this paradigm, we as designers create families of design solutions where <b>parameters</b> inform and customize the solution to fit <b>site, nature, physics, design, usage, or any other</b> requirements a specific problem might have. Instead of <b>manual interpretation</b> of evergrowing complex conditions designers face, we offload parts of the solution to the computer to be dealt with <b>precision</b>.
            <br>
            <br>
            In the years of experimenting and teaching <b>Grasshopper 3D</b> at the <b>Institute for Advanced Architecture of Catalonia</b> I had experience applying this mindset to problems like:<br><b>
            - digitizing design solution to allow free variation;<br>
            - digitizing or processing of physical spaces, objects, or actuations to a usable digital representative model to serve as a simulation or input for further development;<br>
            - cataloging design solutions to explore the visual language of certain form factor;<br>
            - embedding complex mathematical and computational techniques in design to achieve a higher level of uniqueness;<br>
            - investigating the performance of design in physical or environmental conditions to give preliminary understanding in early stages of design;<br>
            - creating interactive and user-friendly experimenting tools for design or digital fabrication.</b>
            <br>
            <br>
            Among these and other situations parametric design serves as an <b>invaluable tool</b> to not only achieve <b>more complex geometrical outcomes</b> but also <b>simplify, streamline and optimize</b> the design process itself allowing designers to focus on <b>creative expression</b>.
            <br>
            <br>
            In light of this <b>Polytope</b> provides services such as <b>translating inspirational material</b> to parametric spatial models; <b>adapting</b> an existing design to the described paradigm; creating a <b>catalog</b> of possible design solutions; <b>exploring complex geometrical forms and patterns</b>; <b>evaluating the performance</b> of a design solution for a given environmental, geometrical or structural conditions; and creation of <b>interfaces</b> abstracting way complex computational processes.
        Esp: >
            Hoy en día <b>computación</b> y <b>diseño</b> ya son inesquivables e inseparables. Nuestras herramientas hacen posible <b>expresar</b> nuestras ideas pero también están forzando <b>un modo único de pensar</b> así añadiendo más soluciones nuevas y únicas.
            <br>
            <br>
            El término <b>diseño paramétrico</b> refiere a un acercamiento cuando el diseño está interpretado como <b>un protocolo</b> no tanto como un solo resultado. En este paradigma nosotros como diseñadores creamos una familia de soluciones donde <b>parámetros</b> nos permiten variar y customizar el desenlace para satisfacer los requisitos sea en <b>local geográfico o urbano, actuación física, o del diseño, o bien de uso o cualquiera otra limitación de problema específica</b>. En vez de interpretar aproximadamente condiciones siempre creciente en complejidad con <b>precisión</b>.
            <br>
            <br>
            En los años de experimentación y enseñanza de <b>Grasshopper 3D</b> en el <b>Instituto de Arquitectura Avanzada de Catalunya</b> he tenido oportunidad aplicar esta mentalidad a problemas alrededor:<br><b>
            - digitalización de solución existente para poder modificarlo libremente;<br>
            - digitalización o procesamiento de espacios, objetos o acciones físicos en equivalentes modelos virtuales para servir como simulación o input para desarrollo;<br>
            - creacion de catalogo de soluciones para explorar lenguaje virtual de un tipo de solución paramétrico;<br>
            - incorporación de técnicas complejas de matemática o computación en diseño para llegar a la unicidad de expresión;<br>
            - investigación de rendimiento de una solución en aspectos de estructura o entorno para proveer intuición preliminar en etapas iniciales de diseño;<br>
            - creación de herramientas interactivas y fáciles de usar para diseño o bien fabricacion digital;</b>
            <br>
            <br>
            Entre estas y otras situaciones el diseño paramétrico sirve como una <b>herramienta imprescindible</b> no solamente para llegar a soluciones <b>más expresivas geométricamente</b>, sino también para <b>facilitar, simplificar y optimizar</b> el proceso de desarrollo en sí, permitiendo al diseñador a enfocar en los <b>aspectos creativos</b>.
            <br>
            <br>
            En luz de esta mentalidad, <b>Polytope</b> presta servicios incluyendo <b>traducción de material inspiracional</b> a modelos paramétricos; <b>adaptación</b> de un diseño existente a paradigma descrita; creación de <b>un catálogo</b> de variantes posibles de una solución; <b>investigación de formas geométricas y patrones complejos</b>; <b>evaluación de rendimiento</b> dentro de unos condiciones relevantes geométricos, ambientales o bien estructurales y tambien creación de <b>interfaces</b> abstrayendo complejidad computacional.
        Cat: >
            A l'era moderna, <b>la computació</b> i <b>el disseny</b> s'han convertit en inseparables. Les nostres eines permeten <b>expressar</b> les nostres idees, però també apliquen <b>una manera de pensar</b> única, obrint solucions noves i úniques.
            <br>
            <br>
            El terme <b>disseny paramètric</b> fa referència a un enfocament en què el disseny es tracta com <b>un protocol</b> en lloc d’un resultat autònom. En aquest paradigma, els dissenyadors creem famílies de solucions de disseny on <b>els paràmetres</b> informen i personalitzen la solució per adaptar-la <b>al lloc, a la naturalesa, a la física, al disseny, a l’ús o a altres requisits</b> que pugui tenir un problema específic. En lloc d’interpretar <b>manualment</b> les condicions complexes que creixen els dissenyadors, descarreguem parts de la solució a l’ordinador per tractar-les amb <b>precisió</b>.
            <br>
            <br>
            Durant els anys d’experimentació i ensenyament de <b>Grasshopper 3D</b> a <b>l’Institut d’Arquitectura Avançada de Catalunya</b>, vaig tenir experiència aplicant aquesta mentalitat a problemes com:<br><b>
            - solució de disseny de digitalització per permetre la variació lliure;<br>
            - digitalització o processament d'espais físics, objectes o actuacions a un model representatiu digital utilitzable per servir de simulació o d'entrada per a un desenvolupament posterior;<br>
            - solucions de disseny de catalogació per explorar el llenguatge visual de determinats factors de forma;<br>
            - Incorporar tècniques matemàtiques i computacionals complexes en el disseny per aconseguir un nivell més elevat de singularitat;<br>
            - investigar el rendiment del disseny en condicions físiques o ambientals per donar una comprensió preliminar en les primeres etapes del disseny;<br>
            - creació d'eines experimentals interactives i fàcils d'utilitzar per al disseny o la fabricació digital.</b>
            <br>
            <br>
            Entre aquestes i altres situacions, el disseny paramètric serveix com <b>una eina inestimable</b> per aconseguir no només <b>resultats geomètrics més complexos</b>, sinó també per a <b>simplificar, racionalitzar i optimitzar</b> el procés de disseny en si mateix, cosa que permet als dissenyadors centrar-se en <b>l’expressió creativa</b>.
            <br>
            <br>
            A la llum d’aquest, <b>Polytope</b> proporciona serveis com <b>la traducció de material inspirador</b> a models espacials paramètrics; <b>adaptar</b> un disseny existent al paradigma descrit; crear <b>un catàleg</b> de possibles solucions de disseny; <b>explorar formes i patrons geomètrics</b> complexos; <b>avaluar el rendiment</b> d'una solució de disseny per a determinades condicions ambientals, geomètriques o estructurals; i creació <b>d'interfícies</b> que abstracteixen processos computacionals complexos.

-   serviceName: Digital-Fabrication-Design
    lang:
        Eng: Design for Digital Fabrication
        Esp: Diseño para fabricación digital
        Cat: Disseny per a fabricació digital
    description:
        Eng: Content coming soon!
        Esp: ¡Contenido viene pronto!
        Cat: Contingut ve pronperament!

-   serviceName: Computational-Design-Courses
    lang:
        Eng: Computational Design Courses
        Esp: Cursos de diseño computacional
        Cat: Cursos de Disseny Computacional
    description:
        Eng: Content coming soon!
        Esp: ¡Contenido viene pronto!
        Cat: Contingut ve pronperament!

-   serviceName: Custom-Scripting
    lang:
        Eng: Custom Scripting
        Esp: Scripts personalizados
        Cat: Scripts personalitzats
    description:
        Eng: Content coming soon!
        Esp: ¡Contenido viene pronto!
        Cat: Contingut ve pronperament!

-   serviceName: 3D-Asset-Developemnt
    lang:
        Eng: 3D Asset Development
        Esp: Desarollo de Assets 3D
        Cat: Desenvolupament d'assets 3D
    description:
        Eng: Content coming soon!
        Esp: ¡Contenido viene pronto!
        Cat: Contingut ve pronperament!
