-   serviceName: Interactive-Visualization
    lang:
        Eng: Interactive Visualization
        Esp: Visualización interactiva
        Cat: Visualització interactiva
    description:
        Eng: >
            <b>Interactive visualization</b> encompasses use of <b>new medium tools</b> to convey the story behind projects to <b>involve target audience</b> on a deeper level and experience projects in a new and specifically tailored way.
            <br>
            <br>
            Each project, depending on the focus and the idea, can be best conveyed in various ways. Mediums Polytope has experience with are:<br><b>
                - Virtual Reailty (standalone or mobile);<br>
                - Web 3D;<br>
                - Augmented Reality (standalona or mobile);<br>
                - Projections;<br>
                - Sensors and actuators.</b>
            <br>
            <br>
            These vary in <b>visual fidelity, types of interaction, scalability, accessibility</b>. Some projects may require combinations of specific aspects.
            <br>
            <br>
            <b>Polytope</b> can provide <b>analysis</b> of idea to fit interactive system and <b>plan steps of development</b>; <b>organization of existing projects</b> to work for it; setup of <b>basic necessary systems</b>; development of <b>custom behaviors</b> necessary for interaction, activation of virtual assets, and User Experiencs (UX); as well as developing <b>details for virtual environments</b>; or <b>support, documentation and guidance</b> in the development.
        Esp: >
            La <b>visualización interactiva</b> abarca el uso de <b>nuevas herramientas de medios</b> para transmitir la historia detrás de los proyectos para <b>involucrar al público objetivo</b> en un nivel más profundo y experimentar los proyectos de una manera nueva y de forma específicamente adaptada.
            <br>
            <br>
            Cada proyecto, según el enfoque y la idea, puede transmitirse mejor de varias formas. Los medios con los que Polytope tiene experiencia son:<br><b>
                -Realidad Virtual(independiente o móvil);<br>
                - Web 3D;<br>
                - Realidad Aumentada (independiente o móvil);<br>
                - Proyecciones;<br>
                - Sensores y actuadores.</b>
            <br>
            <br>
            Estos varían en <b>fidelidad visual, tipos de interacción, escalabilidad, accesibilidad</b>. Algunos proyectos pueden requerir combinaciones de aspectos específicos.
            <br>
            <br>
            <b>Polytope</b> puede proporcionar <b>análisis</b> de la idea para que se ajuste al sistema interactivo y <b>planificar los pasos del desarrollo</b>; <b>organización de proyectos existentes</b> para funcionar con estos medios; configuración de <b>sistemas básicos necesarios</b>; desarrollo de <b>comportamientos personalizados</b> necesarios para la interacción, activación de activos virtuales y experiencias de usuario (UX); además de desarrollar <b>detalles para entornos virtuales</b>; o incluso <b>soporte, documentación y orientación</b> en el processo de desarrollo.
        Cat: >
            La <b>visualització interactiva</b> abasta l'ús de <b>noves eines de mitjans</b> per transmetre la història darrere dels projectes per <b>involucrar el públic objectiu</b> en un nivell més profund i experimentar els projectes d'una manera nova i de forma específicament adaptada.
            <br>
            <br>
            Cada projecte, segons l'enfocament i la idea, pot transmetre millor de diverses formes. Els mitjans amb els quals Polytope té experiència són:<br><b>
                - Realitat Virtual (independent o mòbil);<br>
                - Web 3D;<br>
                - Realitat Augmentada (independent o mòbil);<br>
                - Projeccions;<br>
                - Sensors i actuadors.</b>
            <br>
            <br>
            Aquests varien en <b>fidelitat visual, tipus d'interacció, escalabilitat, accessibilitat</b>. Alguns projectes poden requerir combinacions d'aspectes específics.
            <br>
            <br>
            <b>Polytope</b> pot proporcionar <b>anàlisi</b> de la idea perquè s'ajusti a sistema interactiu i <b>planificar els passos de el desenvolupament</b>; <b>organització de projectes existents</b> per a funcionar amb aquests mitjans; configuració de <b>sistemes bàsics necessaris</b>; desenvolupament de <b>comportaments personalitzats</b> necessaris per a la interacció, activació d'actius virtuals i experiències d'usuari (UX); a més de desenvolupar <b>detalls per a entorns virtuals</b>; o fins i tot <b>suport, documentació i orientació</b> en el proces de desenvolupament.

-   serviceName: Parametric-Design
    lang:
        Eng: Parametric Design
        Esp: Diseño Paramétrico
        Cat: Disseny piramètric
    description:
        Eng: Content coming soon!
        Esp: ¡Contenido viene pronto!
        Cat: Contingut ve pronperament!

-   serviceName: Digital-Fabrication-Design
    lang:
        Eng: Design for Digital Fabrication
        Esp: Diseño para fabricación digital
        Cat: Disseny per a fabricació digital
    description:
        Eng: Content coming soon!
        Esp: ¡Contenido viene pronto!
        Cat: Contingut ve pronperament!

-   serviceName: Computational-Design-Courses
    lang:
        Eng: Computational Design Courses
        Esp: Cursos de diseño computacional
        Cat: Cursos de Disseny Computacional
    description:
        Eng: Content coming soon!
        Esp: ¡Contenido viene pronto!
        Cat: Contingut ve pronperament!

-   serviceName: Custom-Scripting
    lang:
        Eng: Custom Scripting
        Esp: Scripts personalizados
        Cat: Scripts personalitzats
    description:
        Eng: Content coming soon!
        Esp: ¡Contenido viene pronto!
        Cat: Contingut ve pronperament!

-   serviceName: 3D-Asset-Developemnt
    lang:
        Eng: 3D Asset Development
        Esp: Desarollo de Assets 3D
        Cat: Desenvolupament d'assets 3D
    description:
        Eng: Content coming soon!
        Esp: ¡Contenido viene pronto!
        Cat: Contingut ve pronperament!
