name: Jekyll Actions

on:
  push:
    branches:
      - master
      
jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      # Use GitHub Actions' cache to shorten build times and decrease load on servers
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-
            
      - uses: helaili/jekyll-action@2.2.0
        with:
          # The GITHUB_TOKEN secret
          token: ${{ secrets.SITE }}
          # The target branch name the sources get pushed to
          target_branch: gh_pages
